# Site settings
title: Alex Hagen
repo_title: REPOTITLE
email: alexhagen@gmail.com
permalink: /template/:title.html
description: > 
  Welcome to my portfolio. I am currently a Ph.D. seeking student
  at Purdue University in Nuclear Engineering.  This portfolio
  shows some designs, publications, and open source codes that I've
  created. Feel free to email me if you have any ideas, questions, or requests. 
baseurl: "/ah_tcp_serv" # the subpath of your site, e.g. /blog/
url: "http://alexhagen.github.io" # the base hostname & protocol for your site
github_username:  alexhagen

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class
